# REUSE Specification Version 1
version = 1

[[annotations]]
# The glob pattern "*" matches all files in this directory.
# This includes dotfiles like .gitignore and regular files like README.md.
path = [
    "*",
    ".github/*",
    "main/CMakeLists.txt"
]

# 'override' ensures that this information is authoritative and any
# conflicting license information inside the files themselves is ignored.
precedence = "override"

# Your copyright and license information from the header.
SPDX-FileCopyrightText = "2025 Jarif Junaeed <jarif_secure@proton.me>"
SPDX-License-Identifier = "MIT"